CREATE TYPE "AIGenerationStatus" AS ENUM ('QUEUED', 'ANALYZING', 'GENERATING', 'COMPLETED', 'FAILED', 'CANCELLED');
CREATE TYPE "ScenarioStatus" AS ENUM ('DRAFT', 'APPROVED', 'REJECTED');
CREATE TYPE "TestCaseStatus" AS ENUM ('DRAFT', 'APPROVED', 'REJECTED');
CREATE TABLE "AIGenerationRun" ("id" UUID NOT NULL, "testRunId" UUID NOT NULL, "status" "AIGenerationStatus" NOT NULL DEFAULT 'QUEUED', "provider" TEXT NOT NULL, "model" TEXT NOT NULL, "promptVersion" TEXT NOT NULL, "inputSummary" JSONB NOT NULL, "scenarioCount" INTEGER NOT NULL DEFAULT 0, "testCaseCount" INTEGER NOT NULL DEFAULT 0, "error" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "cancelRequestedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AIGenerationRun_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AIGenerationRun_testRunId_createdAt_idx" ON "AIGenerationRun"("testRunId", "createdAt");
CREATE INDEX "AIGenerationRun_testRunId_status_idx" ON "AIGenerationRun"("testRunId", "status");
ALTER TABLE "AIGenerationRun" ADD CONSTRAINT "AIGenerationRun_testRunId_fkey" FOREIGN KEY ("testRunId") REFERENCES "TestRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "TestScenario" ("id" UUID NOT NULL, "testRunId" UUID NOT NULL, "generationRunId" UUID NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "module" TEXT NOT NULL, "category" TEXT NOT NULL, "priority" TEXT NOT NULL, "risk" TEXT NOT NULL, "sourcePageId" UUID, "status" "ScenarioStatus" NOT NULL DEFAULT 'DRAFT', "generationMetadata" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TestScenario_pkey" PRIMARY KEY ("id"));
CREATE INDEX "TestScenario_testRunId_category_status_idx" ON "TestScenario"("testRunId", "category", "status");
CREATE INDEX "TestScenario_sourcePageId_idx" ON "TestScenario"("sourcePageId");
ALTER TABLE "TestScenario" ADD CONSTRAINT "TestScenario_testRunId_fkey" FOREIGN KEY ("testRunId") REFERENCES "TestRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TestScenario" ADD CONSTRAINT "TestScenario_generationRunId_fkey" FOREIGN KEY ("generationRunId") REFERENCES "AIGenerationRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TestScenario" ADD CONSTRAINT "TestScenario_sourcePageId_fkey" FOREIGN KEY ("sourcePageId") REFERENCES "DiscoveredPage"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "TestCase" ("id" UUID NOT NULL, "testRunId" UUID NOT NULL, "generationRunId" UUID NOT NULL, "scenarioId" UUID, "testCaseId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "module" TEXT NOT NULL, "category" TEXT NOT NULL, "priority" TEXT NOT NULL, "severity" TEXT NOT NULL, "preconditions" TEXT NOT NULL, "testData" JSONB NOT NULL, "steps" JSONB NOT NULL, "expectedResult" TEXT NOT NULL, "postconditions" TEXT NOT NULL, "sourcePageId" UUID, "sourceElementId" UUID, "status" "TestCaseStatus" NOT NULL DEFAULT 'DRAFT', "generationSource" TEXT NOT NULL DEFAULT 'AI', "modifiedByUser" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "TestCase_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "TestCase_testRunId_testCaseId_key" ON "TestCase"("testRunId", "testCaseId");
CREATE INDEX "TestCase_testRunId_category_priority_status_idx" ON "TestCase"("testRunId", "category", "priority", "status");
CREATE INDEX "TestCase_sourcePageId_idx" ON "TestCase"("sourcePageId");
CREATE INDEX "TestCase_sourceElementId_idx" ON "TestCase"("sourceElementId");
ALTER TABLE "TestCase" ADD CONSTRAINT "TestCase_testRunId_fkey" FOREIGN KEY ("testRunId") REFERENCES "TestRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TestCase" ADD CONSTRAINT "TestCase_generationRunId_fkey" FOREIGN KEY ("generationRunId") REFERENCES "AIGenerationRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TestCase" ADD CONSTRAINT "TestCase_scenarioId_fkey" FOREIGN KEY ("scenarioId") REFERENCES "TestScenario"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TestCase" ADD CONSTRAINT "TestCase_sourcePageId_fkey" FOREIGN KEY ("sourcePageId") REFERENCES "DiscoveredPage"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TestCase" ADD CONSTRAINT "TestCase_sourceElementId_fkey" FOREIGN KEY ("sourceElementId") REFERENCES "DiscoveredElement"("id") ON DELETE SET NULL ON UPDATE CASCADE;
